@api-service = HD:2001

#@api-service = 127.0.0.1:33146

### Crawl Feed
POST http://{{api-service}}/crawl-requests
Content-Type: application/json

{
    "id": "80bc3136-dac4-4aad-94ea-4f6c0c6648e7",
    "action": "crawl-request",
    "created": "2021-02-21T19:28:18.8220101+00:00",
    "parameters": {
        "uri" : "https://blogs.msdn.microsoft.com/dotnet/feed"
    },
    "metadata": {}
 }

### Crawl Feed - expand child resources
POST http://{{api-service}}/api/crawl
Content-Type: application/json

{
    "id": "80bc3136-dac4-4aad-94ea-4f6c0c6648e7",
    "action": "crawl-request",
    "created": "2021-02-21T19:28:18.8220101+00:00",
    "parameters": {
        "uri" : "https://blogs.msdn.microsoft.com/dotnet/feed",
        "expand" : "child-resources"
    },
    "metadata": {}
}

### With provided metadata
POST http://{{api-service}}/api/crawl
Content-Type: application/json

{
    "id": "80bc3136-dac4-4aad-94ea-4f6c0c6648e7",
    "action": "crawl-request",
    "created": "2021-02-21T19:28:18.8220101+00:00",
    "parameters": {
        "uri" : "https://devblogs.microsoft.com/dotnet/staying-safe-with-dotnet-containers/",
        "id": "d64bc5a5-f2d2-572c-bfbf-b99e5340c0d9",
        "display": "Staying safe with .NET containers",
        "description": "<p>Container-based application deployment and execution has become very common. Nearly all cloud and server app developers we talk to use containers in some way. We mostly hear about public cloud use, but also IoT and have even heard of .NET containers pulled and used over satellite links on cruise ships.</p>\n<p>The post <a rel=\"nofollow\" href=\"https://devblogs.microsoft.com/dotnet/staying-safe-with-dotnet-containers/\">Staying safe with .NET containers</a> appeared first on <a rel=\"nofollow\" href=\"https://devblogs.microsoft.com/dotnet\">.NET Blog</a>.</p>\n",
        "published": "2021-02-11T19:01:56+00:00"
    },
    "metadata": {}
}